###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/window_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class WindowTrace(Component):
    impl = "WindowTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    path = Param(str, required=True)
    bank = Param(int, required=True)
    queue_len = Param(int, required=True)
